### ISSUE TITLE
How to configure MQTT settings ?

### ISSUE THREAD

**Issue by ironslow** [P5Software/RoombaMQTT#1]
Hi,

I successfully provisioned the WIFI setting after the first boot. But, I can't find where to put MQTT settings (server, port, username, password).

thx

**Comment by P5Software** [comment]
When you boot the Arduino, it will create a WiFi network Roomba-xxxxxxx.  Connect to it then point your browser to 192.168.1.1.  Provisioning is there.

I haven’t written the instructions yet. But it’s  the same as the room monitoring device documentation, which I think is posted and public. Let me know if you have issues!

**Comment by P5Software** [comment]
For now, refer to the readme for the room monitoring device, except the SSID will be Roomba-[MAC] instead of RMD-[MAC].
